version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: namc-norcal-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-namc_norcal_portal}
      POSTGRES_USER: ${POSTGRES_USER:-namc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-namc_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - namc-network

  redis:
    image: redis:7-alpine
    container_name: namc-norcal-redis
    ports:
      - "6379:6379"
    networks:
      - namc-network

volumes:
  postgres_data:

networks:
  namc-network:
    driver: bridge 